// <auto-generated />
using System;
using Kitchain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KitchainDbContext))]
    [Migration("20260909090000_AddCourtSubmissions")]
    partial class AddCourtSubmissions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kitchain.Domain.Courts.Amenity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Code");

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Parking"
                        },
                        new
                        {
                            Code = "Restroom"
                        },
                        new
                        {
                            Code = "Shower"
                        },
                        new
                        {
                            Code = "ChangingRoom"
                        },
                        new
                        {
                            Code = "AirConditioning"
                        },
                        new
                        {
                            Code = "PaddleRental"
                        },
                        new
                        {
                            Code = "BallOrEquipmentRental"
                        },
                        new
                        {
                            Code = "ProShop"
                        },
                        new
                        {
                            Code = "FoodAndDrinks"
                        },
                        new
                        {
                            Code = "SeatingOrWaitingArea"
                        },
                        new
                        {
                            Code = "Coaching"
                        },
                        new
                        {
                            Code = "Lockers"
                        },
                        new
                        {
                            Code = "Other"
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BookingMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IndoorOutdoor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surface")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("Courts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courts_BookingMethod", "\"BookingMethod\" IN ('ExternalPlatform', 'Website', 'GoogleForm', 'Phone', 'Message', 'WalkIn', 'Other')");

                            t.HasCheckConstraint("CK_Courts_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_Courts_Currency", "\"CurrencyCode\" IS NULL OR \"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_Courts_DataSource", "\"DataSource\" IN ('OwnerSupplied', 'CommunitySupplied', 'KitchainCurated')");

                            t.HasCheckConstraint("CK_Courts_IndoorOutdoor", "\"IndoorOutdoor\" IN ('Indoor', 'Outdoor', 'Mixed')");

                            t.HasCheckConstraint("CK_Courts_NumberOfCourts", "\"NumberOfCourts\" > 0");

                            t.HasCheckConstraint("CK_Courts_Price", "\"StartingPrice\" IS NULL OR (\"StartingPrice\" >= 0 AND \"CurrencyCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Courts_PriceUnit", "\"PriceUnit\" IS NULL OR (\"StartingPrice\" IS NOT NULL AND \"PriceUnit\" IN ('PerHour', 'PerPerson', 'PerSession'))");

                            t.HasCheckConstraint("CK_Courts_RequiredText", "length(trim(\"Name\")) > 0 AND length(trim(\"City\")) > 0 AND length(trim(\"Address\")) > 0");

                            t.HasCheckConstraint("CK_Courts_Status", "\"Status\" IN ('Draft', 'Published', 'Inactive')");

                            t.HasCheckConstraint("CK_Courts_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtAmenity", b =>
                {
                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<string>("AmenityCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CourtId", "AmenityCode");

                    b.HasIndex("AmenityCode");

                    b.ToTable("CourtAmenities", (string)null);
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtAmenity", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Courts.Court", null)
                        .WithMany("Amenities")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtPhoto", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<string>("AltText").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<Guid>("CourtId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("DisplayOrder").HasColumnType("integer");
                    b.Property<string>("ImageUrl").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                    b.Property<bool>("IsPrimary").HasColumnType("boolean");
                    b.HasKey("Id");
                    b.HasIndex("CourtId").IsUnique().HasDatabaseName("IX_CourtPhotos_OnePrimaryPerCourt").HasFilter("\"IsPrimary\"");
                    b.HasIndex("CourtId", "IsPrimary", "DisplayOrder", "Id").IsDescending(false, true, false, false);
                    b.ToTable("CourtPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtPhotos_DisplayOrder", "\"DisplayOrder\" >= 0");
                            t.HasCheckConstraint("CK_CourtPhotos_ImageUrl", "\"ImageUrl\" ~ '^https?://[^[:space:]/?#@]+([/?#][^[:space:]]*)?$'");
                        });
                    b.HasOne("Kitchain.Domain.Courts.Court", null).WithMany("Photos")
                        .HasForeignKey("CourtId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.Court", b =>
                {
                    b.Navigation("Amenities");
                    b.Navigation("Photos");
                });
            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BookingMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");


                    b.Property<string>("IndoorOutdoor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surface")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("CourtSubmissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtSubmissions_BookingMethod", "\"BookingMethod\" IN ('ExternalPlatform', 'Website', 'GoogleForm', 'Phone', 'Message', 'WalkIn', 'Other')");

                            t.HasCheckConstraint("CK_CourtSubmissions_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_CourtSubmissions_Currency", "\"CurrencyCode\" IS NULL OR \"CurrencyCode\" ~ '^[A-Z]{3}$'");


                            t.HasCheckConstraint("CK_CourtSubmissions_IndoorOutdoor", "\"IndoorOutdoor\" IN ('Indoor', 'Outdoor', 'Mixed')");

                            t.HasCheckConstraint("CK_CourtSubmissions_NumberOfCourts", "\"NumberOfCourts\" > 0");

                            t.HasCheckConstraint("CK_CourtSubmissions_Price", "\"StartingPrice\" IS NULL OR (\"StartingPrice\" >= 0 AND \"CurrencyCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CourtSubmissions_PriceUnit", "\"PriceUnit\" IS NULL OR (\"StartingPrice\" IS NOT NULL AND \"PriceUnit\" IN ('PerHour', 'PerPerson', 'PerSession'))");

                            t.HasCheckConstraint("CK_CourtSubmissions_RequiredText", "length(trim(\"Name\")) > 0 AND length(trim(\"City\")) > 0 AND length(trim(\"Address\")) > 0");

                            t.HasCheckConstraint("CK_CourtSubmissions_Status", "\"Status\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_CourtSubmissions_Timestamps", "\"UpdatedAt\" >= \"SubmittedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionAmenity", b =>
                {
                    b.Property<Guid>("CourtSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AmenityCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CourtSubmissionId", "AmenityCode");

                    b.HasIndex("AmenityCode");

                    b.ToTable("CourtSubmissionAmenities", (string)null);
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionAmenity", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Courts.CourtSubmission", null)
                        .WithMany("Amenities")
                        .HasForeignKey("CourtSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionPhoto", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<string>("AltText").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<Guid>("CourtSubmissionId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("DisplayOrder").HasColumnType("integer");
                    b.Property<string>("ImageUrl").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                    b.Property<bool>("IsPrimary").HasColumnType("boolean");
                    b.HasKey("Id");
                    b.HasIndex("CourtSubmissionId").IsUnique().HasDatabaseName("IX_CourtSubmissionPhotos_OnePrimaryPerCourt").HasFilter("\"IsPrimary\"");
                    b.HasIndex("CourtSubmissionId", "IsPrimary", "DisplayOrder", "Id").IsDescending(false, true, false, false).HasDatabaseName("IX_CourtSubmissionPhotos_Ordered");
                    b.ToTable("CourtSubmissionPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtSubmissionPhotos_DisplayOrder", "\"DisplayOrder\" >= 0");
                            t.HasCheckConstraint("CK_CourtSubmissionPhotos_ImageUrl", "\"ImageUrl\" ~ '^https?://[^[:space:]/?#@]+([/?#][^[:space:]]*)?$'");
                        });
                    b.HasOne("Kitchain.Domain.Courts.CourtSubmission", null).WithMany("Photos")
                        .HasForeignKey("CourtSubmissionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmission", b =>
                {
                    b.Navigation("Amenities");
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}

