// <auto-generated />
using System;
using Kitchain.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kitchain.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KitchainDbContext))]
    [Migration("20260918105135_AddGearFoundation")]
    partial class AddGearFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kitchain.Domain.Courts.Amenity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Code");

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "Parking"
                        },
                        new
                        {
                            Code = "Restroom"
                        },
                        new
                        {
                            Code = "Shower"
                        },
                        new
                        {
                            Code = "ChangingRoom"
                        },
                        new
                        {
                            Code = "AirConditioning"
                        },
                        new
                        {
                            Code = "PaddleRental"
                        },
                        new
                        {
                            Code = "BallOrEquipmentRental"
                        },
                        new
                        {
                            Code = "ProShop"
                        },
                        new
                        {
                            Code = "FoodAndDrinks"
                        },
                        new
                        {
                            Code = "SeatingOrWaitingArea"
                        },
                        new
                        {
                            Code = "Coaching"
                        },
                        new
                        {
                            Code = "Lockers"
                        },
                        new
                        {
                            Code = "Other"
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BookingMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IndoorOutdoor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Surface")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("Courts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Courts_BookingMethod", "\"BookingMethod\" IN ('ExternalPlatform', 'Website', 'GoogleForm', 'Phone', 'Message', 'WalkIn', 'Other')");

                            t.HasCheckConstraint("CK_Courts_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_Courts_Currency", "\"CurrencyCode\" IS NULL OR \"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_Courts_DataSource", "\"DataSource\" IN ('OwnerSupplied', 'CommunitySupplied', 'KitchainCurated')");

                            t.HasCheckConstraint("CK_Courts_IndoorOutdoor", "\"IndoorOutdoor\" IN ('Indoor', 'Outdoor', 'Mixed')");

                            t.HasCheckConstraint("CK_Courts_NumberOfCourts", "\"NumberOfCourts\" > 0");

                            t.HasCheckConstraint("CK_Courts_Price", "\"StartingPrice\" IS NULL OR (\"StartingPrice\" >= 0 AND \"CurrencyCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_Courts_PriceUnit", "\"PriceUnit\" IS NULL OR (\"StartingPrice\" IS NOT NULL AND \"PriceUnit\" IN ('PerHour', 'PerPerson', 'PerSession'))");

                            t.HasCheckConstraint("CK_Courts_RequiredText", "length(trim(\"Name\")) > 0 AND length(trim(\"City\")) > 0 AND length(trim(\"Address\")) > 0");

                            t.HasCheckConstraint("CK_Courts_Status", "\"Status\" IN ('Draft', 'Published', 'Inactive')");

                            t.HasCheckConstraint("CK_Courts_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtAmenity", b =>
                {
                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<string>("AmenityCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CourtId", "AmenityCode");

                    b.HasIndex("AmenityCode");

                    b.ToTable("CourtAmenities", (string)null);
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CourtId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourtPhotos_OnePrimaryPerCourt")
                        .HasFilter("\"IsPrimary\"");

                    b.HasIndex("CourtId", "IsPrimary", "DisplayOrder", "Id")
                        .IsDescending(false, true, false, false);

                    b.ToTable("CourtPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtPhotos_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_CourtPhotos_ImageUrl", "\"ImageUrl\" ~ '^https?://[^[:space:]/?#@]+([/?#][^[:space:]]*)?$'");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BookingMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BookingUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IndoorOutdoor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PriceUnit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SocialUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal?>("StartingPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surface")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("CourtSubmissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtSubmissions_BookingMethod", "\"BookingMethod\" IN ('ExternalPlatform', 'Website', 'GoogleForm', 'Phone', 'Message', 'WalkIn', 'Other')");

                            t.HasCheckConstraint("CK_CourtSubmissions_Coordinates", "(\"Latitude\" IS NULL AND \"Longitude\" IS NULL) OR (\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL AND \"Latitude\" BETWEEN -90 AND 90 AND \"Longitude\" BETWEEN -180 AND 180)");

                            t.HasCheckConstraint("CK_CourtSubmissions_Currency", "\"CurrencyCode\" IS NULL OR \"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_CourtSubmissions_IndoorOutdoor", "\"IndoorOutdoor\" IN ('Indoor', 'Outdoor', 'Mixed')");

                            t.HasCheckConstraint("CK_CourtSubmissions_NumberOfCourts", "\"NumberOfCourts\" > 0");

                            t.HasCheckConstraint("CK_CourtSubmissions_Price", "\"StartingPrice\" IS NULL OR (\"StartingPrice\" >= 0 AND \"CurrencyCode\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_CourtSubmissions_PriceUnit", "\"PriceUnit\" IS NULL OR (\"StartingPrice\" IS NOT NULL AND \"PriceUnit\" IN ('PerHour', 'PerPerson', 'PerSession'))");

                            t.HasCheckConstraint("CK_CourtSubmissions_RequiredText", "length(trim(\"Name\")) > 0 AND length(trim(\"City\")) > 0 AND length(trim(\"Address\")) > 0");

                            t.HasCheckConstraint("CK_CourtSubmissions_Status", "\"Status\" IN ('Pending', 'Approved', 'Rejected')");

                            t.HasCheckConstraint("CK_CourtSubmissions_Timestamps", "\"UpdatedAt\" >= \"SubmittedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionAmenity", b =>
                {
                    b.Property<Guid>("CourtSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AmenityCode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("CourtSubmissionId", "AmenityCode");

                    b.HasIndex("AmenityCode");

                    b.ToTable("CourtSubmissionAmenities", (string)null);
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CourtSubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CourtSubmissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_CourtSubmissionPhotos_OnePrimaryPerCourt")
                        .HasFilter("\"IsPrimary\"");

                    b.HasIndex("CourtSubmissionId", "IsPrimary", "DisplayOrder", "Id")
                        .IsDescending(false, true, false, false)
                        .HasDatabaseName("IX_CourtSubmissionPhotos_Ordered");

                    b.ToTable("CourtSubmissionPhotos", null, t =>
                        {
                            t.HasCheckConstraint("CK_CourtSubmissionPhotos_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_CourtSubmissionPhotos_ImageUrl", "\"ImageUrl\" ~ '^https?://[^[:space:]/?#@]+([/?#][^[:space:]]*)?$'");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.GearBrand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("GearBrands", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearBrands_Identity", "length(trim(\"Name\")) > 0 AND \"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_GearBrands_Time", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.GearDataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PublisherDomain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Id");

                    b.ToTable("GearDataSources", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearDataSources_Required", "length(trim(\"Name\")) > 0 AND (\"Type\" = 'Manual' OR \"Url\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_GearDataSources_Time", "\"LastCheckedAt\" >= \"RetrievedAt\" AND \"CreatedAt\" >= \"RetrievedAt\"");

                            t.HasCheckConstraint("CK_GearDataSources_Type", "\"Type\" IN ('Manufacturer','Retailer','Marketplace','IndependentTest','Editorial','Manual')");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.GearImportCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("BrandSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ManufacturerSku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MatchedVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaddleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PaddleSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("VariantSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("MatchedVariantId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Status", "CreatedAt", "Id");

                    b.ToTable("GearImportCandidates", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearImportCandidates_Decision", "(\"Status\" = 'Pending' AND \"ReviewedAt\" IS NULL AND \"MatchedVariantId\" IS NULL) OR (\"Status\" = 'Rejected' AND \"ReviewedAt\" IS NOT NULL AND \"MatchedVariantId\" IS NULL) OR (\"Status\" = 'Approved' AND \"ReviewedAt\" IS NOT NULL AND \"MatchedVariantId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_GearImportCandidates_Evidence", "\"EvidenceType\" IN ('ManufacturerStated','RetailerStated','IndependentlyMeasured','KitchainVerified')");

                            t.HasCheckConstraint("CK_GearImportCandidates_Positive", "(\"ThicknessMm\" IS NULL OR \"ThicknessMm\" > 0) AND (\"AdvertisedWeightMinOz\" IS NULL OR \"AdvertisedWeightMinOz\" > 0) AND (\"AdvertisedWeightMaxOz\" IS NULL OR \"AdvertisedWeightMaxOz\" > 0) AND (\"LengthInches\" IS NULL OR \"LengthInches\" > 0) AND (\"WidthInches\" IS NULL OR \"WidthInches\" > 0) AND (\"HandleLengthInches\" IS NULL OR \"HandleLengthInches\" > 0) AND (\"GripCircumferenceInches\" IS NULL OR \"GripCircumferenceInches\" > 0) AND (\"SwingWeightKgCm2\" IS NULL OR \"SwingWeightKgCm2\" > 0) AND (\"TwistWeightKgCm2\" IS NULL OR \"TwistWeightKgCm2\" > 0) AND (\"MeasuredWeightOz\" IS NULL OR \"MeasuredWeightOz\" > 0)");

                            t.HasCheckConstraint("CK_GearImportCandidates_Ranges", "(\"AdvertisedWeightMinOz\" IS NULL OR \"AdvertisedWeightMaxOz\" IS NULL OR \"AdvertisedWeightMinOz\" <= \"AdvertisedWeightMaxOz\") AND (\"HandleLengthInches\" IS NULL OR \"LengthInches\" IS NULL OR \"HandleLengthInches\" <= \"LengthInches\")");

                            t.HasCheckConstraint("CK_GearImportCandidates_Shape", "\"Shape\" IS NULL OR \"Shape\" IN ('Standard','Widebody','Hybrid','Elongated','Other')");

                            t.HasCheckConstraint("CK_GearImportCandidates_Time", "\"CreatedAt\" >= \"ObservedAt\" AND (\"ReviewedAt\" IS NULL OR \"ReviewedAt\" >= \"CreatedAt\")");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.Paddle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ModelFamily")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "Slug")
                        .IsUnique();

                    b.HasIndex("Status", "Name", "Id");

                    b.ToTable("GearPaddles", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearPaddles_Identity", "length(trim(\"Name\")) > 0 AND \"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_GearPaddles_Status", "\"Status\" IN ('Draft','Published','Archived')");

                            t.HasCheckConstraint("CK_GearPaddles_Time", "\"UpdatedAt\" >= \"CreatedAt\"");

                            t.HasCheckConstraint("CK_GearPaddles_Year", "\"ReleaseYear\" IS NULL OR \"ReleaseYear\" BETWEEN 1965 AND 2200");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleImage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PaddleVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PaddleVariantId")
                        .IsUnique()
                        .HasFilter("\"IsPrimary\" = TRUE");

                    b.HasIndex("SourceId");

                    b.HasIndex("PaddleVariantId", "SortOrder", "Id");

                    b.ToTable("GearPaddleImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearPaddleImages_Order", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleListing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool?>("InStock")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("OriginalPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("PaddleVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("PaddleVariantId", "LastCheckedAt", "Id");

                    b.ToTable("GearPaddleListings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearPaddleListings_Currency", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_GearPaddleListings_Price", "(\"Price\" IS NULL OR \"Price\" >= 0) AND (\"OriginalPrice\" IS NULL OR \"OriginalPrice\" >= 0)");

                            t.HasCheckConstraint("CK_GearPaddleListings_Time", "\"UpdatedAt\" >= \"CreatedAt\" AND \"CreatedAt\" >= \"LastCheckedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddlePerformanceProfile", b =>
                {
                    b.Property<Guid>("PaddleVariantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Control")
                        .HasColumnType("integer");

                    b.Property<int?>("Forgiveness")
                        .HasColumnType("integer");

                    b.Property<int?>("HandSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("MethodVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("OverallStyle")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<int?>("Spin")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("SweetSpot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaddleVariantId");

                    b.ToTable("GearPerformanceProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearPerformanceProfiles_Method", "length(trim(\"MethodVersion\")) > 0");

                            t.HasCheckConstraint("CK_GearPerformanceProfiles_Ratings", "(\"Power\" IS NULL OR \"Power\" BETWEEN 1 AND 10) AND (\"Control\" IS NULL OR \"Control\" BETWEEN 1 AND 10) AND (\"Forgiveness\" IS NULL OR \"Forgiveness\" BETWEEN 1 AND 10) AND (\"HandSpeed\" IS NULL OR \"HandSpeed\" BETWEEN 1 AND 10) AND (\"Spin\" IS NULL OR \"Spin\" BETWEEN 1 AND 10) AND (\"SweetSpot\" IS NULL OR \"SweetSpot\" BETWEEN 1 AND 10)");

                            t.HasCheckConstraint("CK_GearPerformanceProfiles_Status", "\"Status\" IN ('Draft','Published','Archived')");

                            t.HasCheckConstraint("CK_GearPerformanceProfiles_Style", "\"OverallStyle\" IS NULL OR \"OverallStyle\" IN ('Power','Control','Balanced')");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleSpecificationEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaddleVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("PaddleVariantId", "ObservedAt", "Id");

                    b.ToTable("GearSpecificationEvidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearSpecificationEvidence_Positive", "(\"ThicknessMm\" IS NULL OR \"ThicknessMm\" > 0) AND (\"AdvertisedWeightMinOz\" IS NULL OR \"AdvertisedWeightMinOz\" > 0) AND (\"AdvertisedWeightMaxOz\" IS NULL OR \"AdvertisedWeightMaxOz\" > 0) AND (\"LengthInches\" IS NULL OR \"LengthInches\" > 0) AND (\"WidthInches\" IS NULL OR \"WidthInches\" > 0) AND (\"HandleLengthInches\" IS NULL OR \"HandleLengthInches\" > 0) AND (\"GripCircumferenceInches\" IS NULL OR \"GripCircumferenceInches\" > 0) AND (\"SwingWeightKgCm2\" IS NULL OR \"SwingWeightKgCm2\" > 0) AND (\"TwistWeightKgCm2\" IS NULL OR \"TwistWeightKgCm2\" > 0) AND (\"MeasuredWeightOz\" IS NULL OR \"MeasuredWeightOz\" > 0)");

                            t.HasCheckConstraint("CK_GearSpecificationEvidence_Ranges", "(\"AdvertisedWeightMinOz\" IS NULL OR \"AdvertisedWeightMaxOz\" IS NULL OR \"AdvertisedWeightMinOz\" <= \"AdvertisedWeightMaxOz\") AND (\"HandleLengthInches\" IS NULL OR \"LengthInches\" IS NULL OR \"HandleLengthInches\" <= \"LengthInches\")");

                            t.HasCheckConstraint("CK_GearSpecificationEvidence_Shape", "\"Shape\" IS NULL OR \"Shape\" IN ('Standard','Widebody','Hybrid','Elongated','Other')");

                            t.HasCheckConstraint("CK_GearSpecificationEvidence_Time", "\"CreatedAt\" >= \"ObservedAt\"");

                            t.HasCheckConstraint("CK_GearSpecificationEvidence_Type", "\"Type\" IN ('ManufacturerStated','RetailerStated','IndependentlyMeasured','KitchainVerified')");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ManufacturerSku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("NormalizedSku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PaddleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaddleId", "NormalizedSku")
                        .IsUnique()
                        .HasFilter("\"NormalizedSku\" IS NOT NULL");

                    b.HasIndex("PaddleId", "Slug")
                        .IsUnique();

                    b.HasIndex("PaddleId", "Status");

                    b.ToTable("GearPaddleVariants", null, t =>
                        {
                            t.HasCheckConstraint("CK_GearPaddleVariants_Identity", "length(trim(\"Name\")) > 0 AND \"Slug\" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'");

                            t.HasCheckConstraint("CK_GearPaddleVariants_Status", "\"Status\" IN ('Draft','Published','Archived')");

                            t.HasCheckConstraint("CK_GearPaddleVariants_Time", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CourtNumber")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentServerNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("ServingTeam")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("integer");

                    b.Property<string>("Winner")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "CourtNumber")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\"");

                    b.ToTable("PlayMatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayMatches_Court", "\"CourtNumber\" > 0");

                            t.HasCheckConstraint("CK_PlayMatches_Current", "\"Status\" <> 'Active' OR \"IsCurrent\"");

                            t.HasCheckConstraint("CK_PlayMatches_Scores", "\"TeamAScore\" >= 0 AND \"TeamBScore\" >= 0");

                            t.HasCheckConstraint("CK_PlayMatches_Service", "\"ServingTeam\" IN ('A', 'B') AND \"CurrentServerNumber\" IN (1, 2)");

                            t.HasCheckConstraint("CK_PlayMatches_Status", "(\"Status\" = 'Active' AND \"CompletedAt\" IS NULL) OR (\"Status\" = 'Completed' AND \"CompletedAt\" >= \"StartedAt\" AND \"CompletedAt\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlayMatches_Winner", "\"Winner\" IS NULL OR (\"Status\" = 'Completed' AND \"Winner\" IN ('A', 'B'))");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayMatchPlayer", b =>
                {
                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "Position")
                        .IsUnique();

                    b.ToTable("PlayMatchPlayers", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayMatchPlayers_TeamPosition", "(\"Position\" IN (1, 2) AND \"Team\" = 'A') OR (\"Position\" IN (3, 4) AND \"Team\" = 'B')");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayRallyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CallOut")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentServerNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PointAwarded")
                        .HasColumnType("boolean");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ServingTeam")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("TeamAScore")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBScore")
                        .HasColumnType("integer");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Sequence")
                        .IsUnique();

                    b.ToTable("PlayRallyEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlayRallyEvents_CallOut", "\"CallOut\" IS NULL OR \"CallOut\" IN ('Drive', 'Dink', 'Lob', 'Fault', 'Out', 'Kitchen', 'ServiceBreak', 'WrongCourt')");

                            t.HasCheckConstraint("CK_PlayRallyEvents_Scores", "\"TeamAScore\" >= 0 AND \"TeamBScore\" >= 0");

                            t.HasCheckConstraint("CK_PlayRallyEvents_Sequence", "\"Sequence\" > 0");

                            t.HasCheckConstraint("CK_PlayRallyEvents_Service", "\"ServingTeam\" IN ('A', 'B') AND \"CurrentServerNumber\" IN (1, 2)");

                            t.HasCheckConstraint("CK_PlayRallyEvents_Winner", "\"Winner\" IN ('A', 'B')");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlaySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("GameTo")
                        .HasColumnType("integer");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<int?>("MaximumPlayers")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("NextQueueOrder")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberOfCourts")
                        .HasColumnType("integer");

                    b.Property<string>("RotationMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ScoringMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WinBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.ToTable("PlaySessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaySessions_Capacity", "\"NumberOfCourts\" > 0 AND (\"MaximumPlayers\" IS NULL OR \"MaximumPlayers\" > 0)");

                            t.HasCheckConstraint("CK_PlaySessions_DefaultModes", "\"RotationMode\" IN ('FairRotation', 'WinnersStay', 'ChallengersStay', 'SplitTeams') AND \"ScoringMode\" = 'Traditional' AND \"GameTo\" = 11 AND \"WinBy\" = 2");

                            t.HasCheckConstraint("CK_PlaySessions_JoinCode", "\"JoinCode\" ~ '^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{6}$'");

                            t.HasCheckConstraint("CK_PlaySessions_Mode", "\"Mode\" IN ('QueueOnly', 'LiveScoring')");

                            t.HasCheckConstraint("CK_PlaySessions_Name", "length(trim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_PlaySessions_QueueCounter", "\"NextQueueOrder\" >= 0");

                            t.HasCheckConstraint("CK_PlaySessions_Schedule", "(\"EndDate\" + \"EndTime\") > (\"SessionDate\" + \"StartTime\")");

                            t.HasCheckConstraint("CK_PlaySessions_Status", "\"Status\" IN ('Draft', 'Active', 'Ended')");

                            t.HasCheckConstraint("CK_PlaySessions_Timestamps", "\"UpdatedAt\" >= \"CreatedAt\"");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlaySessionPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AdjustedGamesStarted")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MissedOpportunities")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedDisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<long?>("QueueOrder")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WaitingSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "NormalizedDisplayName")
                        .IsUnique()
                        .HasFilter("NOT \"IsRemoved\"");

                    b.HasIndex("SessionId", "QueueOrder")
                        .IsUnique()
                        .HasFilter("\"QueueOrder\" IS NOT NULL");

                    b.HasIndex("SessionId", "State", "QueueOrder");

                    b.ToTable("PlaySessionPlayers", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlaySessionPlayers_Fairness", "\"AdjustedGamesStarted\" >= 0 AND \"MissedOpportunities\" >= 0");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_Identity", "\"IdentityType\" = 'Guest'");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_Name", "length(trim(\"DisplayName\")) > 0 AND length(trim(\"NormalizedDisplayName\")) > 0");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_Queue", "(\"State\" = 'Waiting' AND \"QueueOrder\" IS NOT NULL AND \"QueueOrder\" > 0) OR (\"State\" IN ('Playing', 'Resting') AND \"QueueOrder\" IS NULL)");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_State", "\"State\" IN ('Waiting', 'Playing', 'Resting')");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_Timestamps", "\"UpdatedAt\" >= \"JoinedAt\"");

                            t.HasCheckConstraint("CK_PlaySessionPlayers_WaitingSince", "(\"State\" = 'Waiting') = (\"WaitingSince\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtAmenity", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Courts.Court", null)
                        .WithMany("Amenities")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtPhoto", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.Court", null)
                        .WithMany("Photos")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionAmenity", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.Amenity", null)
                        .WithMany()
                        .HasForeignKey("AmenityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Courts.CourtSubmission", null)
                        .WithMany("Amenities")
                        .HasForeignKey("CourtSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmissionPhoto", b =>
                {
                    b.HasOne("Kitchain.Domain.Courts.CourtSubmission", null)
                        .WithMany("Photos")
                        .HasForeignKey("CourtSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.GearImportCandidate", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.PaddleVariant", null)
                        .WithMany()
                        .HasForeignKey("MatchedVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Kitchain.Domain.Gear.GearDataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Kitchain.Domain.Gear.GearSpecifications", "Specifications", b1 =>
                        {
                            b1.Property<Guid>("GearImportCandidateId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("AdvertisedWeightMaxOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("AdvertisedWeightMaxOz");

                            b1.Property<decimal?>("AdvertisedWeightMinOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("AdvertisedWeightMinOz");

                            b1.Property<string>("Construction")
                                .HasMaxLength(240)
                                .HasColumnType("character varying(240)")
                                .HasColumnName("Construction");

                            b1.Property<string>("CoreMaterial")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("CoreMaterial");

                            b1.Property<string>("FaceMaterial")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("FaceMaterial");

                            b1.Property<decimal?>("GripCircumferenceInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("GripCircumferenceInches");

                            b1.Property<decimal?>("HandleLengthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("HandleLengthInches");

                            b1.Property<decimal?>("LengthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("LengthInches");

                            b1.Property<decimal?>("MeasuredWeightOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("MeasuredWeightOz");

                            b1.Property<string>("Shape")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Shape");

                            b1.Property<decimal?>("SwingWeightKgCm2")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("SwingWeightKgCm2");

                            b1.Property<decimal?>("ThicknessMm")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("ThicknessMm");

                            b1.Property<decimal?>("TwistWeightKgCm2")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("TwistWeightKgCm2");

                            b1.Property<decimal?>("WidthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("WidthInches");

                            b1.HasKey("GearImportCandidateId");

                            b1.ToTable("GearImportCandidates");

                            b1.WithOwner()
                                .HasForeignKey("GearImportCandidateId");
                        });

                    b.Navigation("Specifications")
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.Paddle", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.GearBrand", null)
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleImage", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.PaddleVariant", null)
                        .WithMany()
                        .HasForeignKey("PaddleVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Gear.GearDataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleListing", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.PaddleVariant", null)
                        .WithMany()
                        .HasForeignKey("PaddleVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Gear.GearDataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddlePerformanceProfile", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.PaddleVariant", null)
                        .WithOne()
                        .HasForeignKey("Kitchain.Domain.Gear.PaddlePerformanceProfile", "PaddleVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleSpecificationEvidence", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.PaddleVariant", null)
                        .WithMany()
                        .HasForeignKey("PaddleVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Gear.GearDataSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Kitchain.Domain.Gear.GearSpecifications", "Specifications", b1 =>
                        {
                            b1.Property<Guid>("PaddleSpecificationEvidenceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("AdvertisedWeightMaxOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("AdvertisedWeightMaxOz");

                            b1.Property<decimal?>("AdvertisedWeightMinOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("AdvertisedWeightMinOz");

                            b1.Property<string>("Construction")
                                .HasMaxLength(240)
                                .HasColumnType("character varying(240)")
                                .HasColumnName("Construction");

                            b1.Property<string>("CoreMaterial")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("CoreMaterial");

                            b1.Property<string>("FaceMaterial")
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("FaceMaterial");

                            b1.Property<decimal?>("GripCircumferenceInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("GripCircumferenceInches");

                            b1.Property<decimal?>("HandleLengthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("HandleLengthInches");

                            b1.Property<decimal?>("LengthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("LengthInches");

                            b1.Property<decimal?>("MeasuredWeightOz")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("MeasuredWeightOz");

                            b1.Property<string>("Shape")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Shape");

                            b1.Property<decimal?>("SwingWeightKgCm2")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("SwingWeightKgCm2");

                            b1.Property<decimal?>("ThicknessMm")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("ThicknessMm");

                            b1.Property<decimal?>("TwistWeightKgCm2")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("TwistWeightKgCm2");

                            b1.Property<decimal?>("WidthInches")
                                .HasPrecision(10, 3)
                                .HasColumnType("numeric(10,3)")
                                .HasColumnName("WidthInches");

                            b1.HasKey("PaddleSpecificationEvidenceId");

                            b1.ToTable("GearSpecificationEvidence");

                            b1.WithOwner()
                                .HasForeignKey("PaddleSpecificationEvidenceId");
                        });

                    b.Navigation("Specifications")
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Gear.PaddleVariant", b =>
                {
                    b.HasOne("Kitchain.Domain.Gear.Paddle", null)
                        .WithMany()
                        .HasForeignKey("PaddleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayMatch", b =>
                {
                    b.HasOne("Kitchain.Domain.Play.PlaySession", null)
                        .WithMany("Matches")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayMatchPlayer", b =>
                {
                    b.HasOne("Kitchain.Domain.Play.PlayMatch", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kitchain.Domain.Play.PlaySessionPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayRallyEvent", b =>
                {
                    b.HasOne("Kitchain.Domain.Play.PlayMatch", null)
                        .WithMany("Rallies")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlaySessionPlayer", b =>
                {
                    b.HasOne("Kitchain.Domain.Play.PlaySession", null)
                        .WithMany("Players")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.Court", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Kitchain.Domain.Courts.CourtSubmission", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlayMatch", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rallies");
                });

            modelBuilder.Entity("Kitchain.Domain.Play.PlaySession", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
